import type { Metadata } from "next";
import "./globals.css";
import MainWrapper from "@/components/layout/mainwrapper/MainWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <MainWrapper>{children}</MainWrapper>
      </body>
    </html>
  );
}
